apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: gitlab-test
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-test
  template:
    metadata:
      labels:
        app: gitlab-test
    spec:
      hostname: localgitlab
      containers:
        - name: gitlab
          image: gitlab/gitlab-ee:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
            - containerPort: 22
              name: ssh
